### ISSUE TITLE
Windows Host Patching Strategy

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#142]
Hi @StefanScherer I wondered if you had any thoughts on patching of a windows estate running lots of windows containers. For example, take the recent malware threat that has hit NHS organizations in the UK and many others worldwide. There has been the need to patch machines quickly to reassure the public and customers. Given the size of the windows base images, this is challenging. So my questions are:

1) Is patching the host enough or must you patch the host and all running containers to secure against threats? When I say patch the containers I really mean rebuilding the images using the latest base image versions released monthly. Have you found an effective way to query for the latest versions automatically?

2) Do you have an idea of a good model for continuously keeping the windows clusters up to date? I think what you have in this repo with appveyor is a nice continuous model, just wondered if you have thoughts on the evolution of this into the inclusion of deployments.

**Comment by StefanScherer** [comment]
Hi @pennywisdom the first real scenario was CVE-2017-0290 that was fixed with last Patch Tuesday, but you still get unpatched machines in the cloud. You at least have to patch the host. I tried it today, you find more details in the latest commits.

1. I don't have automatically version checks for old images used. You can use https://github.com/StefanScherer/winspector to check specific images on the Docker Hub and check if they use the latest Windows base images.

So for example 

```
docker run --rm stefanscherer/winspector golang:nanoserver
```
shows for example the `microsoft/nanoserver:10.0.14393.1066` update layer, so no update to 10.0.14393.1198. So someone could automate that (it's a small Python hack using the Docker Hub API) to check all own Windows Docker images in use.
I also hope that the Docker Security Scanning or other enterprise products will help you there to check for Windows vulnerabilities as well. /CC @friism 

2. Well the pattern should be the same for Linux and Windows. You have to fix host/kernel issues and keep your Linux/Windows images up-to-date.

**Comment by pennywisdom** [comment]
Thanks @StefanScherer winspector is great. FYI for a quick lookup for the latest os version of the windows base image version you can use ``` (Invoke-RestMethod https://registry.hub.docker.com/v2/repositories/microsoft/windowsservercore/tags/latest).images.os_version``` or similar.

**Comment by StefanScherer** [comment]
Thanks @pennywisdom that's a very good query to check the os_version. It seems to work with any Windows image pushed to Docker Hub.
Only thing the metadata has to be added manually to multi-arch images using a manifest list.

**Comment by StefanScherer** [comment]
```
PS C:\> (Invoke-RestMethod https://registry.hub.docker.com/v2/repositories/stefanscherer/winspector/tags/latest).images


size         :
architecture : amd64
variant      :
features     :
os           : windows
os_version   :
os_features  :

size         :
architecture : amd64
variant      :
features     :
os           : linux
os_version   :
os_features  :



PS C:\> (Invoke-RestMethod https://registry.hub.docker.com/v2/repositories/stefanscherer/winspector/tags/windows-1.7.1).images


size         : 401431446
architecture : amd64
variant      :
features     :
os           : windows
os_version   : 10.0.14393.1198
os_features  :
```

**Comment by StefanScherer** [comment]
Oh this is fixed with the upcoming docker manifest command:

```
PS C:\Users\vagrant> (Invoke-RestMethod https://registry.hub.docker.com/v2/repositories/
stefanscherer/winspector/tags/1.7.1-test-pr27455).images


size         :
architecture : amd64
variant      :
features     :
os           : windows
os_version   : 10.0.14393.1198
os_features  :

size         :
architecture : amd64
variant      :
features     :
os           : linux
os_version   :
os_features  :
```
