### ISSUE TITLE
Interested in reworking DockerTLS container in pure powershell?

### ISSUE THREAD

**Issue by artisticcheese** [StefanScherer/dockerfiles-windows#154]
I found a way to generate all neccessary certificates using pure powershell with no requirement for open SSL. Works out of the box with any Windows 10 box and .NET 4.6 and up.

**Comment by StefanScherer** [comment]
That is really great!
So all we need is just one ps1 script on Windows 10/2016. As there still are some steps needed on the host I think it would be great to improve a script like this https://github.com/StefanScherer/docker-windows-box/blob/master/scripts/dockertls.ps1 doing everything without a container.

**Comment by artisticcheese** [comment]
Yes, my snippets as you can see just there to guide the rest of functionality. I don't really need full script since this not I will do as scale or which will require a lot of automation but I think since a lot of people using your container or script in general, I though it will be easier completely remove openSSL and possible container based instantiation and do all of it via WinRM instead.

**Comment by StefanScherer** [comment]
I think I'll keep the container image as it is because it wouldn't look different for users to pull a Docker image. The image itself is not very big so there is no really a need for optimisation here.

I think of other scenarios where someone wants to setup TLS protected Docker hosts without pulling any image in the first place, so a single PS1 script outside of a container would make more sense.

Just for other watchers reading this issue I'll link to your blog post:

https://artisticcheese.wordpress.com/2017/06/10/using-pure-powershell-to-generate-tls-certificates-for-docker-daemon-running-on-windows/

But thanks for the idea. But if someone wants to make that optimisation I'm happy to receive a pull request :-)

**Comment by StefanScherer** [comment]
@artisticcheese Instead of putting the script into a container I think of using your PowerShell commands to provision my Vagrant boxes directly. Playing with the Insider builds is a chicken-egg-problem - each new Insider has a new major number, so "old" insider images on Hub can't be used. So I have to rebuild the dockertls again and again during Insider test phase. The script will appear in insider-docker-machine at some point.
