### ISSUE TITLE
Question about base image switching

### ISSUE THREAD

**Issue by NotMyself** [StefanScherer/dockerfiles-windows#164]
I have a question about this [nodejs dockerfile](https://github.com/StefanScherer/dockerfiles-windows/blob/master/node/6.11/nano/Dockerfile). It uses microsoft/windowsservercore to download nodejs, then switches to microsoft/nanoserver to build the image. 

Is there a reason for using two different windows images to do this?

**Comment by StefanScherer** [comment]
Yes, it is a multi-stage build to result in a small final Docker image with Node.js on top of the nanoserver base image.

I have added the GPG checks just like the Linux version does to check the downloads etc. The GPG binaries don't work inside Nano Server, but they work in the bigger Windows Server Core base image. And the final image should not contain these GPG binaries.

So that's a typical way to do some preparation work in a first stage (like downloading, extracting, checking checksums, or compiling code with a development environment) and then `COPY` deploy from the previous stage (or stages) into the final Docker image.

All what gets pushed to the Docker Hub are the layers in [line 34 - 46 of the last stage](https://github.com/StefanScherer/dockerfiles-windows/blob/450b37e8916f384a18b6ed5fd76ccad4cb5e584c/node/6.11/nano/Dockerfile#L34-L46).

This COPY instruction uses `--from=` with the name of the earlier stage to copy files or directories from.

Please have a look at my blog post from DockerCon earlier this year: https://stefanscherer.github.io/use-multi-stage-builds-for-smaller-windows-images/ what else you can do with multi-stage builds.

**Comment by NotMyself** [comment]
Thanks!
