### ISSUE TITLE
 Windows system call: This operation returned because the timeout period expired. (0x5b4)

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#203]
Hi @StefanScherer 
I have a mssql server container image that I am trying to build (using the [ms image](https://hub.docker.com/r/microsoft/mssql-server-windows-developer/) as the base) however I frequently get the following issue:

Service 'sqldb' failed to build: container 1d285522703e6516ab66ee2a7f87ed4d366c706dbba313570c421e4902dfe84e encountered an error during Start: failure in a Windows system call: This operation returned because the timeout period expired. (0x5b4)

Have you seen this before? I am building on a m4.large AWS EC2 instance and have read that slow storage can be the issue, but I am not entirely sure. The issues seems to stem from starting the SQL SERVER windows service. Strangely I have followed the process used in the Dockerfile from the base image. Any tips for debugging this more effectively?

Thanks for any pointers you can offer.

**Comment by StefanScherer** [comment]
Do you have any antivirus software running as well?

Just found this blog post: https://mdaslam.wordpress.com/tag/docker-windows-server-2016-this-operation-returned-because-the-timeout-period-expired-0x5b4/

Try to turn it off (eg. Windows Defender) and see if the problem still happens frequently.

Or monitor which other processes take up a lot of CPU while starting that container.

I once had this problem https://github.com/docker/compose/issues/4089 while spinning up a lot of containers with docker-compose up.

**Comment by pennywisdom** [comment]
Nope, nothing other that windows defender which i must admit was my suspicion. I will try disabling that. Thanks.

**Comment by StefanScherer** [comment]
Closing now. Feel free to update if you have a solution. Otherwise ask in moby/moby or the dockerfiles repo for mssql for further help.
