### ISSUE TITLE
Chocolatey PS Syntax issue

### ISSUE THREAD

**Issue by bearrito** [StefanScherer/dockerfiles-windows#338]
Hello, I'm running an adapted version of the chocolatey build

![chocolatey](https://user-images.githubusercontent.com/1908139/41130510-1063d6d6-6a85-11e8-902f-5eb52ec47623.png)

This works OK on the host, but the image seems to have issues.

**Comment by Rachel-ResDiary** [comment]
I'm seeing this issue too. The base image I'm using is `microsoft/dotnet-framework:4.7.1`

**Comment by seal-ss** [comment]
Without the instructions in the `Dockerfile` it's hard to help.

I tried a very simple example with the dotnet-framework image and it works.

```Dockerfile
# escape=`
FROM microsoft/dotnet-framework:4.7.1

ENV chocolateyUseWindowsCompression false

RUN powershell -Command `
    iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); `
    choco feature disable --name showDownloadProgress
```

I have built the image with this command:

```
$ docker build -t dotnetchoco .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM microsoft/dotnet-framework:4.7.1
 ---> ccb7c2aa9c87
Step 2/3 : ENV chocolateyUseWindowsCompression false
 ---> Running in 3152cd203226
Removing intermediate container 3152cd203226
 ---> 8e9f789bd2d1
Step 3/3 : RUN powershell -Command     iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'));     choco feature disable --name showDownloadProgress
 ---> Running in dc40f88725e9
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.11.
Downloading 7-Zip commandline tool prior to extraction.
Extracting C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall...
Installing chocolatey on this machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine') 
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell 
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when 
  upgrading from a version of Chocolatey less than 0.9.9. 
  'Batch file could not be found' is also safe to ignore. 
  'The system cannot find the file specified' - also safe.
chocolatey.nupkg file not installed in lib.
 Attempting to locate it from bootstrapper.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
WARNING: Not setting tab completion: Profile file does not exist at 
'C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\Microsoft.PowerShe
ll_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
Chocolatey v0.10.11
Disabled showDownloadProgress
Removing intermediate container dc40f88725e9
 ---> 0eb306f00dae
Successfully built 0eb306f00dae
Successfully tagged dotnetchoco:latest
```

Running a container also works:

```
$ docker run dotnetchoco choco -help
This is a listing of all of the different things you can pass to choco.

Commands

 * list - lists remote or local packages
 * search - searches remote or local packages (alias for list)
 * info - retrieves package information. Shorthand for choco search pkgname --exact --verbose
 * install - installs packages from various sources
...
```

**Comment by Rachel-ResDiary** [comment]
In case it helps anyone else, this is what eventually worked for me:

`# Install Chocolatey
RUN @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin

# New Powershell, so choco is available 
SHELL ["powershell"]

# Choco disable upload progress 
RUN choco feature disable --name showDownloadProgress `

I think the problem was that the Execution Policy for Powershell inside the newly-created container was too restrictive. Hence the `-Execution Policy unrestricted` flag.

The full Dockerfile is;

`# escape=`

FROM jetbrains/teamcity-agent:2018.1-windowsservercore

SHELL ["cmd", "/S", "/C"]

# Install Chocolatey
RUN @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin

# New Powershell, so choco is available 
SHELL ["powershell"]

# Choco disable upload progress 
RUN choco feature disable --name showDownloadProgress 

# Choco install Git
RUN choco install git.install -y

# # Choco install framework v3.5
# RUN choco install dotnet3.5 --version 3.5.20160218  -y     
#^^^ NB: Doesn't work - can't install framework 3.5 in this way in a container
#        See https://stackoverflow.com/questions/44717156/install-net-framework-3-5-on-windows-server-core-docker for details

# Choco install Windows 8 SDK.
RUN choco install windows-sdk-8.1 -y

# Choco install windows Azuree SDK via Chocolatey
RUN powershell choco install windowsazurelibsfornet -y

# Choco install Build Tools for VSS 2013
RUN choco install microsoft-build-tools-2013 -y

# Choco install Build Tools for VSS 2015
RUN choco install microsoft-build-tools --version 14.0.25420.1 -y

#Launch Teamcity Agent
#CMD ["powershell.exe", "-NoProfile", "-Command", "c:/buildagent/run-agent.ps1"] #Do manually for debugging`

Once I did get Chocolatey working, it was by far the cleanest way to install dependencies.

**Comment by StefanScherer** [comment]
Thanks again @Rachel-ResDiary. I could reproduce the problem with the mcr.microsoft.com/windows-insider:10.0.17744.1001 image so we probably hit that problem more often in future Docker images.
