### ISSUE TITLE
1809 / 2019 support for nodejs

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#391]
Hi @StefanScherer, firstly congratulations on your move to Docker! Second, and this is a general query re nodejs and windows 1809/2019. I see that under the hood things have changed regarding volume mounting and how this is now natively visible in terms of the path inside the container. I was wondering if you have found that this resolves the issues with running nodejs against scripts in a volume (especially permissions and finding the paths correctly). Have you found that this has improved things or do the problems still remain and we need to still copy the files from the mounted volume to a location created in the context of the container?

Thanks

**Comment by StefanScherer** [comment]
Thanks @pennywisdom, yes the volume mounting is fixed since 1803 as I mentioned that in https://github.com/nodejs/node/issues/8897#issuecomment-429601955 some months ago.
So it is time to push https://github.com/nodejs/docker-node/pull/362 a little further, the constraint is not to use multi-stage builds. Maybe I find some time to update my PR.

For now you can use my images that already have 1809/2019 support for the nanoserver based images.

**Comment by pennywisdom** [comment]
Thanks @StefanScherer . Hmm I get some strange behaviour still when executing node scripts inside the mount. The mount itself is fine. Looks like its permissions related to me. So looks like great progress with the initial volumes issues :) . I am able to mount the volume, then copy to a new location then run the same scripts without problem. This is for nodejs version 6.16 though so might well be related to this older release.

**Comment by StefanScherer** [comment]
Oh, yes try 8 or 10 which is LTS now.

**Comment by pennywisdom** [comment]
thanks @StefanScherer
